### ISSUE TITLE
dependency on libsqlite3-dev preventing server launch

### ISSUE THREAD

**Issue by flingwing** [makuto/Liked-Saved-Image-Downloader#68]
When I launched the LikedSavedDownloaderServer.py on my freenas jail (BSD 11.3) I got:

```
Traceback (most recent call last):
  File "LikedSavedDownloaderServer.py", line 19, in <module>
    import redditUserImageScraper
  File "/usr/home/ckoulas/redditLikedSavedImageDownloader/redditUserImageScraper.py", line 6, in <module>
    import LikedSavedDatabase
  File "/usr/home/ckoulas/redditLikedSavedImageDownloader/LikedSavedDatabase.py", line 5, in <module>
    import sqlite3
  File "/usr/local/lib/python3.7/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

Doesn't look like I can get sqlite3 in a straightforward way so likely will need a new python environment to get this going unless there are any suggestions.

**Comment by makuto** [comment]
I'm not sure about BSD, but [this tutorial](https://www.osradar.com/how-to-install-sqlite-on-freebsd-12/) seems promising.
Essentially, you need to install the binaries for SQLite3 on your system. I'm not sure how Python detects them though. On Linux, the `-dev` version is also needed, but I don't know if BSD package managers also use that scheme to get header files.

The database is required for storing things like failed download errors, and will eventually enable better browsing features.

**Comment by flingwing** [comment]
appreciate the feedback!
