### ISSUE TITLE
deleted gfycat.com users raised exception

### ISSUE THREAD

**Issue by flingwing** [makuto/Liked-Saved-Image-Downloader#69]
I was not able to get LikedSavedDownloaderServer.py to browse or download content (but it would launch and I could update settings). The webpage stated it wasn't connected to server and download content button didn't seem to do anything.

I did have some success using launching redditUserImageScraper.py
it started downloading content but it seems when it transitioned to downloading imgur content the script hit a deleted user and the below error occurred. 

`[ERROR] Exception: Url https://gfycat.com/<imgur user>raised exception:
	 (404) [imgur user] does not exist.
Traceback (most recent call last):
  File "/Users/[user]/redditLikedSavedImageDownloader/imageSaver.py", line 182, in convertGfycatUrlToWebM
    gfycatUrlInfo = gfycatClient.query_gfy(matches[0])
  File "/usr/local/lib/python3.7/site-packages/gfycat/client.py", line 97, in query_gfy
    raise GfycatClientError(response[ERROR_KEY], r.status_code)
gfycat.error.GfycatClientError: (404) [imgur user] does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "redditUserImageScraper.py", line 224, in <module>
    runLikedSavedDownloader(None)
  File "redditUserImageScraper.py", line 57, in runLikedSavedDownloader
    only_important_messages = settings.settings['Only_important_messages'])
  File "/Users/[user]/redditLikedSavedImageDownloader/imageSaver.py", line 331, in saveAllImages
    url = convertGfycatUrlToWebM(url)
  File "/Users/[user]/redditLikedSavedImageDownloader/imageSaver.py", line 186, in convertGfycatUrlToWebM
    LikedSavedDatabase.db.addUnsupportedSubmission(submission, errorMessage)
NameError: name 'submission' is not defined
`

**Comment by makuto** [comment]
I'm glad you got it running!
I'll see if I can take a look at this tomorrow morning :).

**Comment by makuto** [comment]
Can you please open a separate issue for your LikedSavedDownloader issue? (the connection lost issue).

**Comment by flingwing** [comment]
can do
