### ISSUE TITLE
'NoneType' object attribute error with Imgur

### ISSUE THREAD

**Issue by flingwing** [makuto/Liked-Saved-Image-Downloader#72]
`Traceback (most recent call last):
  File "redditUserImageScraper.py", line 226, in <module>
    runLikedSavedDownloader(None)
  File "redditUserImageScraper.py", line 58, in runLikedSavedDownloader
    only_important_messages = settings.settings['Only_important_messages'])
  File "/Users/[user]/dev/redditLikedSavedImageDownloader/imageSaver.py", line 335, in saveAllImages
    url = imgurDownloader.convertImgurIndirectUrlToImg(submission, imgur_auth, url)
  File "/Users/[user]/dev/redditLikedSavedImageDownloader/imgurDownloader.py", line 35, in convertImgurIndirectUrlToImg
    imgurClient = imgur.ImgurClient(imgurAuth.clientId, imgurAuth.clientSecret)
AttributeError: 'NoneType' object has no attribute 'clientId'`

Got to 25% through the ~1000 submissions list from 9% on previous run, solid gains!

**Comment by makuto** [comment]
This one should be solvable by providing Imgur authentication in Settings. I will need to look into adding a more helpful error.

**Comment by makuto** [comment]
Do you have Imgur Authentication set up?
