### ISSUE TITLE
LSID does not work anymore

### ISSUE THREAD

**Issue by Z0pyrus** [makuto/Liked-Saved-Image-Downloader#88]
While using the release version, this is happening when I try to download stuff:
```
WARNING:tornado.access:404 GET /favicon.ico (127.0.0.1) 0.61ms
RunScriptWebSocket: Received message  {"command":"runScript","user":"likedSavedBrowserClient"}
RunScriptWebSocket: Command  runScript
RunScriptWebSocket: Starting script
Reading settings from settings file with most recent timestamp, which was:
LOCAL_settings_from_server.txt
If you want to read from a different settings file, make it more recent
Intializing database at LikedSaved.db
No Gfycat Client ID and/or Gfycat Client Secret was provided. This is required to download Gfycat media reliably.
Output: output
Process Process-2:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 258, in _bootstrap
  File "multiprocessing/process.py", line 93, in run
  File "redditUserImageScraper.py", line 51, in runLikedSavedDownloader
  File "redditUserImageScraper.py", line 116, in getSubmissionsToSave
  File "redditScraper.py", line 106, in getRedditUserLikedSavedSubmissions
  File "praw/reddit.py", line 129, in __init__
  File "praw/config.py", line 72, in __init__
  File "praw/config.py", line 98, in _initialize_attributes
  File "praw/config.py", line 31, in _config_boolean
AttributeError: '_NotSet' object has no attribute 'lower'
Lost connection to subprocess!
```

When I'm building from source I'll get this (Without poetry):
```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.10) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "LikedSavedDownloaderServer.py", line 30, in <module>
    import PasswordManager
  File "/home/test/Liked-Saved-Image-Downloader/PasswordManager.py", line 6, in <module>
    from passlib.context import CryptContext
ModuleNotFoundError: No module named 'passlib'
```
This could be fixed when I use Poetry, but gave me another error:
```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.10) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Updating dependencies
Resolving dependencies... (23.5s)

  RuntimeError

  The dependency name for pixivpy does not match the actual package's name: pixivpy3

  at /usr/local/lib/python3.8/dist-packages/poetry/puzzle/provider.py:291 in get_package_from_directory
      287│         )
      288│
      289│         if name and name != package.name:
      290│             # For now, the dependency's name must match the actual package's name
    → 291│             raise RuntimeError(
      292│                 "The dependency name for {} does not match the actual package's name: {}".format(
      293│                     name, package.name
      294│                 )
      295│             )
```
I could fix this by deleting all packages and run it poetry and than the "old" command.

**Comment by memst** [comment]
@makuto Re: last code block.

At some point `pixivpy` [got renamed](https://github.com/upbit/pixivpy/commit/5ceeeb293a41075d0e0e7cd243bdd5cda5c2f743) to `pixivpy3`. Their minimum required python version is now also 3.7.

Do we bump the dependency or completely remove it? I haven't actually found a place where pixivpy used these days.

**Comment by memst** [comment]
@Z0pyrus
```
No Gfycat Client ID and/or Gfycat Client Secret was provided. This is required to download Gfycat media reliably.
```

Have you added your API key to Gfycat in the settings? You can do that on http://localhost:8888/settings. The api keys are easily got from here: https://developers.gfycat.com/signup/#/keys.

**Comment by memst** [comment]
I couldn't recreate the issue. Try updating `pyproject.toml` to the following and running the poetry setup. I did that in a fresh vm and it seems to have run fine. Ignore my comment about gfycat earlier.

```
[tool.poetry]
name = "content-collector"
version = "0.9.0"
description = "Save content you enjoy!"
authors = ["Macoy Madson <macoy@macoy.me>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7.0"
praw = "^6.1.1"
pytumblr = "^0.1.0"
py3-pinterest = "^1.1.0"
jsonpickle = "^1.4.1"
tornado = "^6.0.4"
youtube-dl = "^2020.7.28"
gfycat = { git = "https://github.com/ankeshanand/py-gfycat", branch = "master" }
pixivpy3 = { git = "https://github.com/upbit/pixivpy", branch = "master" }
passlib = {version = "^1.7.2", optional = true}
bcrypt = {version = "^3.1.0", optional = true}
argon2_cffi = {version = "^20.1.0", optional = true}
imgurpython = "^1.1.7"

[tool.poetry.extras]
security = ["passlib", "bcrypt", "argon2_cffi"]

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

**Comment by makuto** [comment]
Hi, sorry for the delay. For whatever reason I haven't been getting notifications on this repository.
Gfycat is a bit tricky: there are two different ways to download. One is via youtube-dl, the other is via the Gfycat API. The instance I run uses the Gfycat API, which I think I got the best results out of.

**Comment by makuto** [comment]
Closed because it is stale.
